// Curated playlist categories shown on the homepage.
// Each category is driven by one or more YouTube search queries, cached
// server-side (see services/cacheService.js) so the homepage never triggers
// a live YouTube API call on every visit.
module.exports = [
  {
    id: "sufi-romance",
    name: "Sufi & Romance",
    icon: "🎻",
    gradient: ["#c471ed", "#7f5af0"],
    queries: ["best bollywood sufi romantic hindi songs playlist"],
  },
  {
    id: "love",
    name: "Love",
    icon: "❤️",
    gradient: ["#ff5da2", "#ff8a65"],
    queries: ["best bollywood romantic love hindi songs hits"],
  },
  {
    id: "dance",
    name: "Dance",
    icon: "💃",
    gradient: ["#2de2e6", "#7f5af0"],
    queries: ["best bollywood dance hindi hits playlist"],
  },
  {
    id: "party",
    name: "Party",
    icon: "🎉",
    gradient: ["#ffd23f", "#ff2ea6"],
    queries: ["best bollywood party hindi songs anthems"],
  },
  {
    id: "dj",
    name: "DJ & Remix",
    icon: "🎧",
    gradient: ["#7f5af0", "#2de2e6"],
    queries: ["best bollywood dj remix hindi songs playlist"],
  },
  {
    id: "90s",
    name: "90s Hits",
    icon: "📼",
    gradient: ["#ff8a65", "#7f5af0"],
    queries: ["best bollywood 90s hindi songs hits"],
  },
  {
    id: "classics",
    name: "Classics",
    icon: "🎶",
    gradient: ["#f5d76e", "#c471ed"],
    queries: ["timeless bollywood classic hindi songs"],
  },
  {
    id: "70s",
    name: "70s Hits",
    icon: "🕺",
    gradient: ["#f6416c", "#f9d423"],
    queries: ["best bollywood 70s hindi songs hits"],
  },
  {
    id: "80s",
    name: "80s Hits",
    icon: "🕹️",
    gradient: ["#7028e4", "#e5b2ca"],
    queries: ["best bollywood 80s hindi songs hits"],
  },
  {
    id: "pop-rap",
    name: "Pop & Rap",
    icon: "🎤",
    gradient: ["#00c9ff", "#92fe9d"],
    queries: ["best indian pop rap hindi hits playlist"],
  },

  // "Vibe" playlists - each modeled on a real everyday-India scene/persona,
  // same idea as sites like oldmonk.vercel.app or hornokplease.xyz: a
  // specific mood/setting instead of a decade or genre label.
  {
    id: "corporate-life",
    name: "Corporate Life",
    icon: "💼",
    gradient: ["#00c9ff", "#7f5af0"],
    queries: ["hindi english corporate office life songs chai break playlist"],
  },
  {
    id: "old-monk",
    name: "Old Monk Nights",
    icon: "🥃",
    gradient: ["#8b5e3c", "#f5d76e"],
    queries: ["bollywood daaru party 80s 90s hindi songs old is gold"],
  },
  {
    id: "loha-lakkad",
    name: "Loha Lakkad",
    icon: "🏋️",
    gradient: ["#f6416c", "#f9d423"],
    queries: ["hindi gym workout motivational bollywood songs high energy"],
  },
  {
    id: "mandir-radio",
    name: "Mandir Radio",
    icon: "🛕",
    gradient: ["#ffb347", "#ff5e62"],
    queries: ["hindi bhajan kirtan aarti devotional songs"],
  },
  {
    id: "gaon-ki-khud",
    name: "Gaon Ki Khud",
    icon: "⛰️",
    gradient: ["#43cea2", "#185a9d"],
    queries: ["pahadi garhwali kumaoni hindi mountain folk songs"],
  },
  {
    id: "kaun-disha-mein",
    name: "Kaun Disha Mein",
    icon: "🌊",
    gradient: ["#4facfe", "#00f2fe"],
    queries: ["hindi soulful spiritual folk journey songs"],
  },
  {
    id: "dard-e-ishq",
    name: "Dard-e-Ishq",
    icon: "💔",
    gradient: ["#ee0979", "#ff6a00"],
    queries: ["dard bhare sad heartbreak hindi bollywood songs"],
  },
  {
    id: "raju-mistri",
    name: "Raju Mistri",
    icon: "🔧",
    gradient: ["#f7971e", "#ffd200"],
    queries: ["hindi romantic sentimental everyday desi songs"],
  },
  {
    id: "deluxe-saloon",
    name: "Deluxe Saloon",
    icon: "💈",
    gradient: ["#ff512f", "#dd2476"],
    queries: ["barber saloon hits hindi retro songs playlist -bus -rickshaw -truck"],
  },
  {
    id: "bus-driver",
    name: "Bus Driver Dhaba",
    icon: "🚌",
    gradient: ["#f83600", "#f9d423"],
    queries: ["80s 90s hindi bhojpuri punjabi haryanvi road trip songs"],
  },
  {
    id: "horn-ok-please",
    name: "Horn OK Please",
    icon: "🚛",
    gradient: ["#ff8008", "#ffc837"],
    queries: ["trucker dhaba gt road highway hindi punjabi gaadi gaane songs -accident -crash -news -viral -bus -saloon"],
  },
  {
    id: "auto-wala",
    name: "Auto Wala",
    icon: "🛺",
    gradient: ["#f7b733", "#fc4a1a"],
    queries: ["auto rickshaw wale bollywood hindi gaane -bus -truck -saloon -barber"],
  },
  {
    id: "chai-ki-tapri",
    name: "Chai Ki Tapri",
    icon: "☕",
    gradient: ["#c79081", "#dfa579"],
    queries: ["chai tapri hindi bollywood indie folk soulful songs"],
  },

  // Trendy multi-language playlists. `relevanceLanguage` overrides the
  // Hindi default (see cacheService.js) so these actually surface
  // Marathi/Punjabi/English results instead of being drowned out by it.
  {
    id: "marathi-beats",
    name: "Marathi Beats",
    icon: "🧡",
    gradient: ["#f7931e", "#f15a24"],
    queries: ["latest marathi songs hit playlist"],
    relevanceLanguage: "mr",
  },
  {
    id: "punjabi-vibes",
    name: "Punjabi Vibes",
    icon: "🎶",
    gradient: ["#ff416c", "#ff4b2b"],
    queries: ["latest punjabi songs bhangra hit playlist"],
    relevanceLanguage: "pa",
  },
  {
    id: "english-hits",
    name: "English Hits",
    icon: "🌍",
    gradient: ["#00c6ff", "#0072ff"],
    queries: ["latest english pop hit songs playlist"],
    relevanceLanguage: "en",
  },
  {
    id: "hindi-new-hits",
    name: "New Hindi Hits",
    icon: "🔥",
    gradient: ["#f857a6", "#ff5858"],
    queries: ["latest new bollywood hindi songs 2025 hit playlist"],
  },
];
